### ISSUE TITLE
Youtube quality

### ISSUE THREAD

**Issue by mathieuthibault** [BellezaEmporium/query-streamlink#27]
Hello,

Is there a way to force a youtube live stream quality with query-streamlink ? Tried the (old) values like https://www.youtube.com/watch?v=xxxxxxxxxx?vq=hd1080 but it obviously doesn't work anymore.

For dailymotion, I saw the workaround in api.key with the live-x.m3u8 value replaced (and that's working well!), but youtube url's in index.m3u8 are totally different and much more complicated. 

Maybe by forcing the script to select a specific stream ID (as we can grab the quality IDs with youtube-dl -F).

Thanks for the great work! Le script fonctionne parfaitement ;-)

**Comment by BellezaEmporium** [comment]
I would need to reinstantiate the quality option if that's the case. It has been removed due to lack of usage.

Concerning the script, ravi de voir qu'il fonctionne niquel !

**Comment by mathieuthibault** [comment]
> I would need to reinstantiate the quality option if that's the case. It has been removed due to lack of usage.
> 
> Concerning the script, ravi de voir qu'il fonctionne niquel !

Hello,

Thanks for replying. Yes, if the quality option can be available again, that would be great (and quitte usefull for several services, not only YouTube).
Hope that's possible!

Merci bcp 🙏

**Comment by BellezaEmporium** [comment]
I've readded the quality setting. Feel free to check. Closing this issue.
