### ISSUE TITLE
TF1 Plugin

### ISSUE THREAD

**Issue by campones** [BellezaEmporium/query-streamlink#34]
salut

je me demandais, vu que le maintainer de streamlink n' exprime aucun interet pour "fix" le plugin de tf1 group, est ce que vous seriez interessé par le faire (si ce n'est pas déja fait) .

merci

**Comment by BellezaEmporium** [comment]
Il faudrait que j'implémente un système de login pour récupérer le lien en question. N'ayant actuellement que peu de temps, je ne peux garantir que cela arrive dans les jours qui viennent.

**Comment by campones** [comment]
Je comprend parfaitement et c'est déja gentil de m' avoir répondu.
Je lui ai signalé le problème fin mai, on est bientot décembre c'est pour ça que je cherchais à vous contacter

j' ai l impression que depuis la fin 2022, la team qui gérait streamlink s'est un peu déchiré au sujet des dons ou quelque chose dans le style et il est un peu seul maintenant. mais sans plugin fonctionnel, le script n' a pratiquement aucun interet.. d' ailleurs je m' en sers pratiquement plus a part pour dailymotion

**Comment by BellezaEmporium** [comment]
Je suis en train de m'y pencher, lentement mais sûrement.
https://github.com/BellezaEmporium/streamlink/blob/master/src/streamlink/plugins/tf1.py

**Comment by campones** [comment]
Salut
c'est super vraiment je te remercie

**Comment by campones** [comment]
au fait j' ai pas demandé mais pour que ça fonctionne il faut utiliser ton fork de streamlink ou je peux juste copier le plugin ?

sinon moi j' obtiens ça  avec la dernière version de streamlink

` streamlink --tf1-username xxx@mail.fr --tf1-password xxx https://www.tf1.fr/tmc/direct
[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tmc/direct
Traceback (most recent call last):
  File "/usr/local/bin/streamlink", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 929, in main
    handle_url()
  File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 551, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 449, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/usr/local/lib/python3.10/dist-packages/streamlink/plugin/plugin.py", line 369, in streams
    ostreams = self._get_streams()
  File "/usr/local/lib/python3.10/dist-packages/streamlink/plugins/tf1.py", line 184, in _get_streams
    if not self.login(self.url):
  File "/usr/local/lib/python3.10/dist-packages/streamlink/plugins/tf1.py", line 157, in login
    self.session_url,
AttributeError: 'TF1' object has no attribute 'session_url'
`

**Comment by BellezaEmporium** [comment]
> au fait j' ai pas demandé mais pour que ça fonctionne il faut utiliser ton fork de streamlink ou je peux juste copier le plugin ?
> 
> sinon moi j' obtiens ça avec la dernière version de streamlink
> 
> > streamlink --tf1-username [xxx@mail.fr](mailto:xxx@mail.fr) --tf1-password xxx https://www.tf1.fr/tmc/direct
> > [cli][info] streamlink is running as root! Be careful!
> > [cli][info] Found matching plugin tf1 for URL https://www.tf1.fr/tmc/direct
> > Traceback (most recent call last):
> > File "/usr/local/bin/streamlink", line 8, in 
> > sys.exit(main())
> > File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 929, in main
> > handle_url()
> > File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 551, in handle_url
> > streams = fetch_streams(plugin)
> > File "/usr/local/lib/python3.10/dist-packages/streamlink_cli/main.py", line 449, in fetch_streams
> > return plugin.streams(stream_types=args.stream_types,
> > File "/usr/local/lib/python3.10/dist-packages/streamlink/plugin/plugin.py", line 369, in streams
> > ostreams = self._get_streams()
> > File "/usr/local/lib/python3.10/dist-packages/streamlink/plugins/tf1.py", line 184, in _get_streams
> > if not self.login(self.url):
> > File "/usr/local/lib/python3.10/dist-packages/streamlink/plugins/tf1.py", line 157, in login
> > self.session_url,
> > AttributeError: 'TF1' object has no attribute 'session_url

Je recommande pas pour l'instant d'utiliser ma version car c'est encore en phase de test, mais ça serait le but oui.

**Comment by BellezaEmporium** [comment]
Réessayez avec le dernier fix. Tout fonctionne comme prévu.

**Comment by campones** [comment]
merci en effet la ça marche impeccablement

**Comment by BellezaEmporium** [comment]
Problème résolu.

**Comment by campones** [comment]
par contre je retrouve ce problème de désynchro audio video , un peu le meme souci que j' avais avec france tv.  (mais la pareil j' utilise plus streamlink pour france tv...)

**Comment by BellezaEmporium** [comment]
> par contre je retrouve ce problème de désynchro audio video , un peu le meme souci que j' avais avec france tv. (mais la pareil j' utilise plus streamlink pour france tv...)

A savoir si ça vient dans le passage de qualité ou si c'est lors d'une coupure inopinée. Streamlink faisant le décodage en direct c'est possible que ça soit un problème de ressources utilisées, quelque chose dans Streamlink qui flanche ou bien le player vidéo qui à du mal.

**Comment by campones** [comment]
sur france tv j ai jamais pu vraiment résoudre cette histoire.  c'est vrai que si tu utilises vlc ça ne se produit pas.  en tout cas je ne crois pas. 
ça arrive  aléatoirement, la par exemple j' ai relancé le flux de ton plugin et  de suite c'est bien synchro cette fois ci.  mais d' expérience ça peut désynchroniser dans 10 min , une heure, ..   vu que ça s' est produit une fois je pense que ça se reproduira..

normalement ça s' améliore un peu quand j' ajoute 

/usr/local/bin/streamlink --ffmpeg-ffmpeg "/usr/local/bin/ffmpeg" --ffmpeg-audio-transcode "aac" --ffmpeg-fout "flv" "https://www.france.tv/france-2/direct.html" best (...)

**Comment by campones** [comment]
en fait ce souci vient du fait que maintenant france tv utilisent du streaming avec audio video séparéet streamlink doit remuxer le flux..  c'est p-e le cas aussi chez tf1 désormais  (je présume)

**Comment by BellezaEmporium** [comment]
TF1 utilise un back-up pour les streams "iPhone" qui ne peuvent donc pas avoir accès aux technos DRM actuelles. De souvenir, index_0 à index_7 sont pour les qualités de stream, index_8 sert uniquement pour l'audio.

**Comment by campones** [comment]
ah, tout le reste est passé en drm?

**Comment by campones** [comment]
en meme temps, pas vraiment surprenant,  presque tous l' utilisent maintenant..

**Comment by BellezaEmporium** [comment]
> ah, tout le reste est passé en drm?

Les streams de TF1 sont tous en DRM de base, oui.

**Comment by campones** [comment]
salut ! 
franchement ça marche tres bien, je n' utilise que tf1 actuellement mais aucun décalage ni rien  c'est super
je te remercie a nouveau

**Comment by campones** [comment]
salut! 
tu comprends maintenant l' origine de ma requete?.. 
désolé mais ce gars c'est un gros con et je pèse mes mots et  je suis meme pas surpris qu' il l' ai pas intégré a la nouvelle release de streamlink. 
j aurai meme pas du faire la réflexion en fait.
